name: Update Homebrew Tap

on:
  push:
    tags:
      - "v*"

jobs:
  update-tap:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout tap repo
        uses: actions/checkout@v3
        with:
          repository: matejstastny/homebrew-dusk
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: main

      - name: Download release archive
        run: |
          VERSION=${GITHUB_REF#refs/tags/}
          curl -L -o dusk.tar.gz https://github.com/matejstastny/dusk/releases/download/$VERSION/dusk-$VERSION.tar.gz
          SHA256=$(sha256sum dusk.tar.gz | cut -d ' ' -f 1)
          echo "SHA256=$SHA256" >> $GITHUB_ENV

      - name: Update formula
        run: |
          sed -i "s/^  version \".*\"/  version \"${GITHUB_REF#refs/tags/}\"/" Formula/dusk.rb
          sed -i "s/^  sha256 \".*\"/  sha256 \"$SHA256\"/" Formula/dusk.rb

      - name: Commit & push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add Formula/dusk.rb
          git commit -m "Update dusk to ${GITHUB_REF#refs/tags/}"
          git push origin main
